name: Build Rust on Nails DevContainer

on:
  push:
    branches:
    - main
    paths:
    - 'dev-env-as-code/**'
    - 'nails-devcontainer/**'
    # Exclude this as it is set by semantic release
    - '!dev-env-as-code/Dockerfile.devcontainer'
    - '!nails-devcontainer/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and cache multi-arch image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/purtontech/rust-on-nails-devcontainer:temp-tag --load dev-env-as-code

    # If this is a release
    #   create release notes
    #   set the docker version
    #   
    - name: Semantic Release
      run: | 
        npm i -D @semantic-release/exec
        npm i -D @semantic-release-plus/docker
        npm i -D @semantic-release/git
        npx semantic-release

    - name: "Publish Templates"
      uses: devcontainers/action@v1
      with:
        publish-templates: "true"
        base-path-to-templates: "./nails-devcontainer"
        generate-docs: "true"

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}