name: Build Rust on Nails DevContainer

on:
  push:
    branches:
      - main
    paths:
      - 'dev-env-as-code/**'
      - 'nails-devcontainer/**'
      - '.github/workflows/**'
      # Exclude this as it is set by semantic release
      - '!dev-env-as-code/Dockerfile.devcontainer'
      - '!nails-devcontainer/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONTAINER_NAME: purtontech/rust-on-nails-devcontainer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Docker file (AMD64)
        run: |
          docker build --platform amd64 -t $CONTAINER_NAME dev-env-as-code
          docker push $CONTAINER_NAME
      
      - name: Build Docker file (ARM64)
        run: |
          docker build --platform arm64 -t $CONTAINER_NAME dev-env-as-code
          docker push $CONTAINER_NAME

      # If this is a release
      #   create release notes
      #   set the docker version
      #   
      - name: Semantic Release
        id: semantic_release
        run: | 
          npm i -D @semantic-release/exec
          npm i -D @semantic-release-plus/docker
          npm i -D @semantic-release/git
          npx semantic-release

      - name: Check Semantic Release Outputs
        run: |
          echo "New release published: ${{ steps.semantic_release.outputs.new-release-published }}"
          echo "Version: ${{ steps.semantic_release.outputs.version }}"
 
      - name: Tag and Push Docker Image
        if: ${{ steps.semantic_release.outputs.new-release-published == 'true' }}
        run: |
          docker pull $CONTAINER_NAME:latest
          docker tag $CONTAINER_NAME:latest $CONTAINER_NAME:${{ steps.semantic_release.outputs.version }}
          docker push $CONTAINER_NAME:${{ steps.semantic_release.outputs.version }}

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./nails-devcontainer"
          generate-docs: "true"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
